// <auto-generated />
using Blazor.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Blazor.Migrations
{
    [DbContext(typeof(BlazorContext))]
    partial class BlazorContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Blazor.Models.Object3d", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.HasKey("Id");

                    b.ToTable("Objects");
                });

            modelBuilder.Entity("Blazor.Models.Object3d", b =>
                {
                    b.OwnsOne("Blazor.Models.Vector3", "Color", b1 =>
                        {
                            b1.Property<int>("Object3dId")
                                .HasColumnType("int");

                            b1.Property<float>("X")
                                .HasColumnType("real");

                            b1.Property<float>("Y")
                                .HasColumnType("real");

                            b1.Property<float>("Z")
                                .HasColumnType("real");

                            b1.HasKey("Object3dId");

                            b1.ToTable("Objects");

                            b1.WithOwner()
                                .HasForeignKey("Object3dId");
                        });

                    b.OwnsOne("Blazor.Models.Vector3", "Position", b1 =>
                        {
                            b1.Property<int>("Object3dId")
                                .HasColumnType("int");

                            b1.Property<float>("X")
                                .HasColumnType("real");

                            b1.Property<float>("Y")
                                .HasColumnType("real");

                            b1.Property<float>("Z")
                                .HasColumnType("real");

                            b1.HasKey("Object3dId");

                            b1.ToTable("Objects");

                            b1.WithOwner()
                                .HasForeignKey("Object3dId");
                        });

                    b.OwnsOne("Blazor.Models.Vector3", "Size", b1 =>
                        {
                            b1.Property<int>("Object3dId")
                                .HasColumnType("int");

                            b1.Property<float>("X")
                                .HasColumnType("real");

                            b1.Property<float>("Y")
                                .HasColumnType("real");

                            b1.Property<float>("Z")
                                .HasColumnType("real");

                            b1.HasKey("Object3dId");

                            b1.ToTable("Objects");

                            b1.WithOwner()
                                .HasForeignKey("Object3dId");
                        });

                    b.Navigation("Color")
                        .IsRequired();

                    b.Navigation("Position")
                        .IsRequired();

                    b.Navigation("Size")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
